fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  links:
    - { 'v1.1': 'master'}
  targets:
    - html
    - dirhtml
  doc-root:
    - 'sitemap.xml'
    - '.htaccess'
  branch-root: []
...